### ISSUE TITLE
Allow SOCKS5/SOCKS4a to resolve DNS on the proxy

### ISSUE THREAD

**Issue by Sytten** [sujiacong/libsocks_client#1]
Both protocols support sending the domain in the `CONNECT` packet.

**Comment by sujiacong** [comment]
This is currently supported in SOCKS5/SOCKS4a. You can use the following code to parse DNS from the server side.
`let mut client = SocksClientBuilder::new(proxyip, proxyport).socks4a().build_tcp_client();
let mut stream = client.connect_hostname("www.baidu.com", 80).await?;`
You can refer to a SOCKS testing tool I wrote. [sockstest](https://github.com/sujiacong/sockstest/blob/main/src/main.rs)

**Comment by sujiacong** [comment]
It should be noted that the Dante SOCKS server does not support SOCKS4a
