### ISSUE TITLE
Reduce allocations by re-using buffer

### ISSUE THREAD

**Issue by Sytten** [sujiacong/libsocks_client#2]
The library does a lot of allocations for the various buffers of requests/responses. The `Client` could allocate a buffer similar to what tokio-socks does here: https://github.com/sticnarf/tokio-socks/blob/master/src/tcp/socks5.rs#L271-L273

**Comment by sujiacong** [comment]
Thank you for your suggestion. I have added a Vec<u8> buffer structure to support client buffer reuse, which is available in version 0.1.2
